% Close and clear
close all
clear all

% Load libraries
pkg load signal

% Load data
path = '/media/jortiz/datax/projects/INAIL_EC2/MyoArmbandDataset/PreTrainingDataset/Male0/training0/';
labels = [ ...
  'Neutral         '; ...
  'Radial Deviation'; ...
  'Wrist Flexion   '; ...
  'Ulnar Deviation '; ...
  'Wrist Extension '; ...
  'Hand Close      '; ...
  'Hand Open       '];

for i = 0:13
  datafile = ['classe_' int2str(i) '.dat'];
  gesture_fnc(path, datafile, labels(mod(i, 7) + 1, :));
end